#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["MVC/MVC.csproj", "MVC/"]
COPY ["OnlineAuction.BLL.Interface/OnlineAuction.BLL.Interface.csproj", "OnlineAuction.BLL.Interface/"]
COPY ["OnlineAuction.Entities/OnlineAuction.Entities.csproj", "OnlineAuction.Entities/"]
COPY ["OnlineAuction.BLL/OnlineAuction.BLL.csproj", "OnlineAuction.BLL/"]
COPY ["OnlineAuction.DAL.Interface/OnlineAuction.DAL.Interface.csproj", "OnlineAuction.DAL.Interface/"]
COPY ["OnlineAuction.DAL/OnlineAuction.DAL.csproj", "OnlineAuction.DAL/"]
RUN dotnet restore "MVC/MVC.csproj"
COPY . .
WORKDIR "/src/MVC"
RUN dotnet build "MVC.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MVC.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MVC.dll"]